name: Auto message for PR's and Issues
description: Automatically send hello message to the first PR and Issue for new contributor.
branding:
  icon: message-square
  color: yellow
on: [pull_request, issues]
jobs:
  build:
    name: Hello new contributor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hi! Welcome to the Andes project 🎉! Thank you for your first issue, and thank you for being a new member of the Andes Community 😃"
          pr-message: "Hi! Welcome to the Andes project 🎉! Thank you for your first pull request, and thank you for being a new member of the Andes Community 😃"